const neighbourhoodsAndSubneighbourhoods: { [key: string]: string[] } = {
    "Črnomerec": [
        "Bijenik",
        "Črnomerec",
        "Fraterščica",
        "Gornje Selo",
        "Gornje Vrapče",
        "Gornji Lukšić",
        "Jelenovac",
        "Krvarić",
        "Kustošija",
        "Lukšić",
        "Mikulići",
        "Sveti Duh",
        "Šestinski dol",
        "Vrhovec",
        "Završje",
    ],
    "Donja Dubrava": [
        "Čulinec",
        "Donja Dubrava",
        "Dubrava",
        "Krčevine",
        "Resnički gaj",
        "Retkovec",
        "Trnava",
    ],
    "Brezovica": [
        "Brezovica",
        "Brebernica",
        "Demerje",
        "Desprim",
        "Donji Dragonožec",
        "Donji Trpuci",
        "Drežnik Brezovički",
        "Goli Breg",
        "Gornji Dragonožec",
        "Gornji Trpuci",
        "Grančari",
        "Havidić Selo",
        "Horvati",
        "Hudi Bitek",
        "Kupinečki Kraljevec",
        "Lipnica",
        "Odranski Obrež",
        "Starjak",
        "Strmec",
        "Zadvorsko",
    ],
    "Donji Grad": ["Donji grad"],
    "Gornja Dubrava": [
        "Branovec",
        "Budaki",
        "Cesari",
        "Čučerje",
        "Čugovec",
        "Čuki",
        "Dankovec",
        "Degidovec",
        "Dubec",
        "Dudaki",
        "Fabijanići",
        "Furdini",
        "Gorni Dankovec",
        "Gornja Dubrava",
        "Gornji Slanovec",
        "Grad mladih",
        "Grana",
        "Granešina",
        "Jalševec",
        "Klaka",
        "Medvedski breg",
        "Micudaji",
        "Mihovci",
        "Miroševec",
        "Naglići",
        "Novaki",
        "Novoselčina",
        "Novoselec",
        "Oporovec",
        "Orešići",
        "Poljanice",
        "Studentski grad",
        "Svibovci",
        "Trnovčica",
        "Trstenik",
        "Trupeljaki",
        "Žgulići",
    ],
    "Gornji Grad - Medveščak": [
        "Britanac",
        "Centar",
        "Dolac",
        "Gornji grad",
        "Gupčeva zvijezda",
        "Kaptol",
        "Kraljevec",
        "Ksaver",
        "Medveščak",
        "Mirogoj",
        "Pantovčak",
        "Prekrižje",
        "Ribnjak",
        "Šalata",
        "Tuškanac",
        "Voćarsko naselje",
        "Zelengaj",
    ],
    "Maksimir": [
        "Donji Bukovac",
        "Gornji Bukovac",
        "Lašćina",
        "Maksimir",
        "Ravnice",
        "Remete",
        "Srebrnjak",
        "Svetice",
    ],
    "Novi Zagreb - Istok": [
        "Bundek",
        "Buzin",
        "Dugave",
        "Hrelić",
        "Jakuševec",
        "Kamenarka",
        "Sloboština",
        "Sopot",
        "Središće",
        "Travno",
        "Utrina",
        "Veliko Polje",
        "Zapruđe",
    ],
    "Novi Zagreb - Zapad": [
        "Blato",
        "Botinec",
        "Donji Čehi",
        "Glogovec",
        "Gornji Čehi",
        "Hrašće Turopoljsko",
        "Hrvatski Leskovac",
        "Ježdovec",
        "Kajzerica",
        "Lanište",
        "Lučko",
        "Mala Mlaka",
        "Podbrežje",
        "Odra",
        "Otočec",
        "Otok",
        "Remetinec",
        "Savski gaj",
        "Siget",
        "Sveta Klara",
        "Trnsko",
        "Trokut",
    ],
    "Peščenica - Žitnjak": [
        "Bogdani",
        "Borongaj",
        "Borongajski lug",
        "Ivanja Reka",
        "Borovje",
        "Donje Svetice",
        "Dubec",
        "Ferenščica",
        "Folnegovićevo naselje",
        "Gate - Gmajna",
        "Kozari",
        "Kozari bok",
        "Kozari put",
        "Peščenica",
        "Petruševec",
        "Resničina",
        "Resnik",
        "Savica - Šanci",
        "Struge",
        "Trstik",
        "Volovčica",
        "Vukomerec",
        "Žitnjak",
    ],
    "Podsljeme": [
        "Bačun",
        "Bidrovec",
        "Dedići",
        "Deščevec",
        "Dolje",
        "Gračani",
        "Kraljičin zdenac",
        "Markuševec",
        "Mlinovi",
        "Popovec",
        "Slanovec",
        "Sljeme",
    ],
    "Sesvete": [
        "Adamovec",
        "Belovar",
        "Blaguša",
        "Bok",
        "Brestje",
        "Brestovčina",
        "Budenec",
        "Cerje",
        "Divjače",
        "Dobrodol",
        "Donja zemlja",
        "Donje polje",
        "Drenčec",
        "Dugava",
        "Đurđekovec",
        "Gajišće",
        "Gajec",
        "Glavnica Donja",
        "Glavnica Gornja",
        "Glavničica",
        "Goranec",
        "Gornje grmlje",
        "Gornje polje",
        "Gornje šume",
        "Iver",
        "Jesenovec",
        "Kašina",
        "Kašinska Sopnica",
        "Kobiljak",
        "Kraljevečki Novaki",
        "Krči",
        "Kučilovina",
        "Kućanec",
        "Laz",
        "Leskovec",
        "Lug",
        "Lužan",
        "Magdalena",
        "Markovo polje",
        "Mokrica",
        "Moravče",
        "Novi Jelkovec",
        "Paruževina",
        "Planina Donja",
        "Planina Gornja",
        "Plavišče",
        "Pod Magdalenom",
        "Popovec",
        "Poredje",
        "Prekvršje",
        "Prepuštovec",
        "Selčina",
        "Sesvete",
        "Sesvetska sela",
        "Sesvetska selnica",
        "Sesvetski Kobiljak",
        "Sesvetski Kraljevec",
        "Setice",
        "Siget",
        "Soblinec",
        "Sodol",
        "Sopnica",
        "Šašinovec",
        "Šimunčevec",
        "Trdica",
        "Trdice",
        "Vretenec",
        "Vuger Selo",
        "Vugrovec Donji",
        "Vugrovec Gornji",
        "Vurnovec",
        "Zavječe",
        "Žerjavinec",
    ],
    "Stenjevec": [
        "Donje Vrapče",
        "Jankomir",
        "Malešnica",
        "Savska Opatovina",
        "Stenjevec",
        "Špansko",
    ],
    "Trešnjevka - Jug": [
        "Gajevo",
        "Gredice",
        "Horvati",
        "Jarun",
        "Knežija",
        "Prečko",
        "Srednjaci",
        "Staglišće",
        "Vrbani",
    ],
    "Trešnjevka - Sjever": [
        "Rudeš",
        "Trešnjevka",
        "Voltino",
    ],
    "Trnje": [
        "Cvjetno naselje",
        "Kanal",
        "Kruge",
        "Martinovka",
        "Savica",
        "Sigečica",
        "Trnje",
        "Vrbik",
    ],
    "Zagreb - Okolica": [
        "Brezovica",
        "Dumovec",
    ],
};

export function GetSubneighbourhoodsInNeighbourhood(neighbourhoods: string): string[] {
    return neighbourhoodsAndSubneighbourhoods[neighbourhoods] || [];
}

export function GetAllDistricts(): string[] {
    return Object.keys(neighbourhoodsAndSubneighbourhoods).sort();
}

export function GetAllSubneighbourhoods(): string[] {
    const allSubneighbourhoods = new Set<string>();
    for (const district in neighbourhoodsAndSubneighbourhoods) {
        neighbourhoodsAndSubneighbourhoods[district].forEach(sub => {
            allSubneighbourhoods.add(sub);
        });
    }
    return Array.from(allSubneighbourhoods).sort();
}

export function GetNeighbourhoodFromSubneighbourhood(subneighbourhood: string): string | null {
    for (const neighbourhood in neighbourhoodsAndSubneighbourhoods) {
        if (neighbourhoodsAndSubneighbourhoods[neighbourhood].includes(subneighbourhood)) {
            return neighbourhood;
        }
    }
    return null; // if the neighbourhood is not found
}